export const ADD_BOOKS = "ADD_BOOKS"
export const DELETE_BOOK = "DELETE_BOOK"
export const DELETE_ALL_BOOK = "DELETE_ALL_BOOK"

export const FECT_BOOKS_LOADING = 'FECT_BOOKS_LOADING'
export const FECT_BOOKS_SUCCESS = 'FECT_BOOKS_SUCCESS'
export const FECT_BOOKS_ERROR = 'FECT_BOOKS_ERROR'